### ISSUE TITLE
User-can-search-by-zipcode

### ISSUE THREAD

**Issue by cyulin17** [cyulin17/boba-finder#1]
## 💰 Motivation

Boba enthusiasts can find the nearest boba tea shops.

## 📐 Plan

Create a search bar and connect with google places API.

## 🖼️ Wireframes

![User-can-search-by-zipcode-desktop](https://user-images.githubusercontent.com/78944582/126255377-38e7823d-2662-42c8-ade8-e0f5e8252ef0.png)

![User-can-search-by-zipcode-mobile](https://user-images.githubusercontent.com/78944582/126255416-de65bb6d-c8a7-4a60-aec7-84da3dd5d091.png)

## ✅ Task List

- [x] Create a navigation bar with logo and favorites. (with a tag)
- [x] Add a image div and set the background image
- [x] Add a search bar
- [x] Create a div for searching result
- [x]  Google places API
- [x] Google Map API
- [x] create search function
- [x] turn number value to stars (rating)
- [x] Remove all CSS styling that had no effect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
