### ISSUE TITLE
User-can-view-store-information

### ISSUE THREAD

**Issue by cyulin17** [cyulin17/boba-finder#2]
## 💰 Motivation

Boba enthusiasts can find more information about the store.

## 📐 Plan

Use Google Maps places API to get store information. (hours/photos/reviews)

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a eventListener when users click the the store.
- [x] Create store information page layout.
- [x] Load the information from Google Maps Places API.
